[package]
name = "speech_recognition_poc"
version = "0.1.0"
authors = ["vvv <valentin.blind@gmail.com>", "vvg <guilhem.radonde@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
